### PR TITLE
Resources monitoring impl

### PR DESCRIPTION
**Pull request by Kavaldrin**
Initial version: Implementation of additional process monitoring metrics and maybe some improvements, but we will see.
(Clangformat will be used after review)

### CODE REVIEW

**Comment by awegrzyn** [comment]
@Kavaldrin Could you please rebase and fix conflicts? If you need any help just lemme know.

**Comment by awegrzyn** [comment]
...or actually we can merge it as it is and then I'll do the change.

**Comment by Kavaldrin** [comment]
@awegrzyn  sure, I thought it would be easier to use existing mechanism for metrics detection in O2 core framework, which is based on format -> single metric - single value. That's why I made vector<Metric> instead of single Metric.

**Comment by awegrzyn** [comment]
I don't think this values are meant to be displayed in the DebugGUI, are they?

**Comment by Kavaldrin** [comment]
@awegrzyn I'm not sure because DebugGUI is not working for me :^(
But for some reason those metrics are parsed and then saved in container.

https://github.com/AliceO2Group/AliceO2/blob/dev/Framework/Core/src/runDataProcessing.cxx
line 524

**Comment by awegrzyn** [comment]
Some DPL internal metric with `[METRIC]` prefix are, the rest is left alone.
So I'd go as single metric. Lemme know if you need any help.

**Comment by Kavaldrin** [comment]
@awegrzyn ok sure and thanks

**Comment by Kavaldrin** [comment]
@awegrzyn As I understand should I go back to vector of metrics?

**Comment by awegrzyn** [comment]
Hi,
To not to block you please do so, I was not aware that the analysis will run differently.
If there will be changes to be done at the later stage I'll do it myself and coordinate it with Giulio.

**Comment by awegrzyn** [comment]
ok I can proceed with merge but I think I'll need to open another PR to remove all files that got fixed with `clang-format`.

**Comment by awegrzyn** [comment]
@Kavaldrin Could you just document added metric in README?
https://github.com/AliceO2Group/Monitoring#process-monitoring

**Comment by Kavaldrin** [comment]
@awegrzyn sure

**Comment by awegrzyn** [comment]
https://github.com/AliceO2Group/Monitoring/pull/204

**Pull request closed without merging**
