### PR TITLE
Metric verbositiy policy with regex

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by awegrzyn** [comment]
@ktf Is this anywhere close to what you requested? It allows to set a regex per verbosity, eg. ```
Metric::setVerbosityPolicy(Verbosity::Prod, std::regex("myMetric", std::regex::optimize));
```

**Comment by ktf** [comment]
Do I understand correctly that I need to do it per metric? Why not per backend?

**Comment by awegrzyn** [comment]
This is to overwrite default metric verbosity, and you can define single regex per verbosity.
Backend verbosity can be set via URL as described in here: https://github.com/AliceO2Group/Monitoring#monitoring-instance

Eg. By default metric verbosity is `Info` (2), if you use `Prod` (3) backend (`stdout:///prod`) no metric will be sent. You can overwrite metric verbosity to `Prod` (3) by running `setVerbosityPolicy("Verbosity::Prod", ...)`.

Lemme know if you need something different.

**Comment by ktf** [comment]
Sorry, I missed it was `static`. Looks like what I wanted, yes.

**Pull request merged**
