### PR TITLE
[WIP] Add travis build

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by awegrzyn** [comment]
Indeed, this is just to verify that everything compiles outside the scope of `aliBuild`. I could easily add `codechecker`.
The problem is that more complex repos (like `QualityControl`) may timeout as the they require many more dependencies. The solution is to download pre-compiled dependencies as it's done in FairRoot: https://github.com/FairRootGroup/FairRoot/blob/e860d52634e0c7ececf8b7b39d70f0076d5bb93d/.travis.yml#L28

**Comment by ktf** [comment]
Another thing you could try to do is to setup travis to cache aliBuild tarballs, effectively speeding up the build even using aliBuild.

**Comment by awegrzyn** [comment]
@ktf Sounds like good idea, I was not aware of it, thanks.

**Comment by ktf** [comment]
https://docs.travis-ci.com/user/caching/

**Pull request merged**
